package:
  name: openpmd-api
  version: 0.14.4

source:
  url: https://github.com/openPMD/openPMD-api/archive/0.14.4.tar.gz
  sha256: 42b7bcd043e772d63f0fe0e5e70da411f001db10096d5b8be797ffc88e786379
  patches:
    - 1199.patch

requirements:
  run:
    - numpy
    - libhdf5
    - zlib

test:
  imports:
    - openpmd_api

build:
  script: |
    pip install -U "setuptools>=57.4.0" pipx pybind11[global]
    python -m pipx install "cmake==3.22"
    export PATH="$(python3 -c 'import site; print(site.USER_BASE)')/bin:${PATH}"
    pip install --upgrade pybind11[global] -t $PYODIDE_ROOT/packages/.artifacts/

    export HDF5_ROOT=$PYODIDE_ROOT/packages/libhdf5/build/libhdf5-1.12.1/build/hdf5
    export ZLIB_ROOT=$PYODIDE_ROOT/packages/zlib/build/zlib-1.2.11
    export CMAKE_PREFIX_PATH=$HDF5_ROOT:$ZLIB_ROOT:${CMAKE_PREFIX_PATH}

    cp $PYODIDE_ROOT/packages/openpmd-api/FindHDF5.cmake $PYODIDE_ROOT/.docker_home/.local/pipx/venvs/cmake/lib/python3.9/site-packages/cmake/data/share/cmake-3.22/Modules/FindHDF5.cmake

    export EMSCRIPTEN=$PYODIDE_ROOT/emsdk/emsdk/upstream/emscripten
    export CXXFLAGS="${CXXFLAGS} -mmutable-globals"
    export openPMD_CMAKE_CMAKE_CROSSCOMPILING_EMULATOR="$PYODIDE_ROOT/emsdk/emsdk/node/14.18.2_64bit/bin/node"
    export openPMD_CMAKE_Python_INCLUDE_DIR=$PYODIDE_ROOT/cpython/installs/python-3.9.5/include/python3.9/
    export openPMD_CMAKE_Python_INCLUDE_DIR=$PYODIDE_ROOT/cpython/installs/python-3.9.5/include/python3.9/
    export openPMD_CMAKE_pybind11_DIR=$PYODIDE_ROOT/packages/.artifacts/pybind11/share/cmake/pybind11
    export openPMD_CMAKE_openPMD_USE_INTERNAL_PYBIND11=OFF
    export openPMD_CMAKE_openPMD_USE_HDF5=ON
    export openPMD_CMAKE_CMAKE_INSTALL_LIBDIR=lib
    export openPMD_CMAKE_CMAKE_TOOLCHAIN_FILE=$PYODIDE_ROOT/emsdk/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake
    export openPMD_CMAKE_CMAKE_PROJECT_openPMD_INCLUDE=$PYODIDE_ROOT/packages/openpmd-api/overwriteProp.cmake
    export openPMD_CMAKE_CMAKE_VERBOSE_MAKEFILE=ON
    export openPMD_CMAKE_HDF5_FIND_DEBUG=TRUE
    export openPMD_CMAKE_HDF5_INCLUDE_DIRS=$HDF5_ROOT/include
    export openPMD_CMAKE_HDF5_LIBRARIES="$HDF5_ROOT/lib/libhdf5.a;$ZLIB_ROOT/lib/libz.a"
    export openPMD_CMAKE_HDF5_DIR=$HDF5_ROOT
    export openPMD_CMAKE_HDF5_IS_PARALLEL=FALSE
    export openPMD_CMAKE_HDF5_FOUND=ON
    export openPMD_CMAKE_HDF5_VERSION=1.12.1

    export openPMD_CMAKE_HDF5_C_INCLUDE_DIRS=$HDF5_ROOT/include
    export openPMD_CMAKE_HDF5_C_LIBRARIES="$HDF5_ROOT/lib/libhdf5.a;$ZLIB_ROOT/lib/libz.a"
    export openPMD_CMAKE_HDF5_C_COMPILER_NO_INTERROGATE=ON
    export openPMD_CMAKE_HDF5_C_FOUND=ON

    export SETUPTOOLS_EXT_SUFFIX=".emscripten_wasm32.so"
