package:
  name: openpmd-api
  version: 0.14.4

source:
  url: https://github.com/openPMD/openPMD-api/archive/0.14.4.tar.gz
  sha256: 42b7bcd043e772d63f0fe0e5e70da411f001db10096d5b8be797ffc88e786379
  patches:
    - 1199.patch

requirements:
  run:
    - numpy
    - libhdf5
    - zlib

test:
  imports:
    - openpmd_api

build:
  script: |
    pip install -U pipx pybind11[global]
    python -m pipx install cmake
    export PATH="$(python3 -c 'import site; print(site.USER_BASE)')/bin:${PATH}"
    pip install --upgrade pybind11[global] -t $PYODIDE_ROOT/packages/.artifacts/

    export CMAKE_PREFIX_PATH=$PYODIDE_ROOT/packages/libhdf5/build/libhdf5-1.12.1/build/hdf5:$PYODIDE_ROOT/packages/zlib/build/zlib-1.2.11:${CMAKE_PREFIX_PATH}

    export EMSCRIPTEN=/src/emsdk/emsdk/upstream/emscripten
    export CXXFLAGS="${CXXFLAGS} -mmutable-globals"
    export openPMD_CMAKE_CMAKE_CROSSCOMPILING_EMULATOR="$PYODIDE_ROOT/emsdk/emsdk/node/14.18.2_64bit/bin/node"
    export openPMD_CMAKE_Python_INCLUDE_DIR=$PYODIDE_ROOT/cpython/installs/python-3.9.5/include/python3.9/
    export openPMD_CMAKE_Python_INCLUDE_DIR=$PYODIDE_ROOT/cpython/installs/python-3.9.5/include/python3.9/
    export openPMD_CMAKE_pybind11_DIR=$PYODIDE_ROOT/packages/.artifacts/pybind11/share/cmake/pybind11
    export openPMD_CMAKE_openPMD_USE_INTERNAL_PYBIND11=OFF
    export openPMD_CMAKE_CMAKE_INSTALL_LIBDIR=lib
    export openPMD_CMAKE_CMAKE_TOOLCHAIN_FILE=$PYODIDE_ROOT/emsdk/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake
    export openPMD_CMAKE_CMAKE_PROJECT_openPMD_INCLUDE=$PYODIDE_ROOT/packages/openpmd-api/overwriteProp.cmake
    export openPMD_CMAKE_CMAKE_VERBOSE_MAKEFILE=ON
